import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand:    "var(--brand)",
        accent:   "var(--accent)",
        surface: {
          DEFAULT: "var(--bg-card)",
          elevated:"var(--bg-elevated)",
          glass:   "var(--bg-glass)",
        },
        ink: {
          DEFAULT: "var(--text)",
          muted:   "var(--text-muted)",
          faint:   "var(--text-faint)",
        },
        line: {
          DEFAULT: "var(--border)",
          bright:  "var(--border-bright)",
          brand:   "var(--border-brand)",
        },
        /* legacy ds-* kept for any missed refs */
        ds: {
          brand:        "#a78bfa",
          brandDark:    "#7c3aed",
          brandLight:   "rgba(167,139,250,0.12)",
          dark:         "#0a0a0f",
          darkSurface:  "#111118",
          text:         "#f0eeff",
          textMuted:    "#9491b4",
          textLight:    "#5b5880",
          textWarm:     "#7c789e",
          bg:           "#0a0a0f",
          bgSubtle:     "#111118",
          bgHover:      "rgba(255,255,255,0.07)",
          bgWhite:      "#ffffff",
          bgWarmSand:   "#16161f",
          border:       "rgba(255,255,255,0.06)",
          borderWarm:   "rgba(255,255,255,0.09)",
          borderDark:   "rgba(255,255,255,0.14)",
          error:        "#f87171",
          focus:        "#a78bfa",
          warning:      "#fb923c",
        },
      },
      fontFamily: {
        sans:    ["Inter", "system-ui", "-apple-system", "sans-serif"],
        display: ["Syne", "Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "ds-display": ["4rem",    { lineHeight: "1.10", fontWeight: "700" }],
        "ds-h1":      ["3.25rem", { lineHeight: "1.10", fontWeight: "700" }],
        "ds-h2":      ["2.3rem",  { lineHeight: "1.20", fontWeight: "700" }],
        "ds-h3":      ["2rem",    { lineHeight: "1.20", fontWeight: "700" }],
        "ds-h4":      ["1.6rem",  { lineHeight: "1.20", fontWeight: "600" }],
        "ds-h5":      ["1.3rem",  { lineHeight: "1.30", fontWeight: "600" }],
        "ds-h6":      ["1.06rem", { lineHeight: "1.40", fontWeight: "600" }],
        "ds-body-lg": ["1.10rem", { lineHeight: "1.70", fontWeight: "400" }],
        "ds-body":    ["0.9375rem",{ lineHeight: "1.65", fontWeight: "400" }],
        "ds-nav":     ["0.875rem",{ lineHeight: "1.25", fontWeight: "500" }],
        "ds-sm":      ["0.8125rem",{ lineHeight: "1.55", fontWeight: "400" }],
        "ds-xs":      ["0.75rem", { lineHeight: "1.40", fontWeight: "400" }],
        "ds-label":   ["0.6875rem",{ lineHeight: "1.60", fontWeight: "500", letterSpacing: "0.06em" }],
        "ds-mono":    ["0.875rem",{ lineHeight: "1.60", fontWeight: "400" }],
      },
      boxShadow: {
        "ds-card":    "var(--shadow-card)",
        "ds-glow":    "var(--shadow-glow)",
        "ds-modal":   "var(--shadow-modal)",
        "ds-input":   "var(--shadow-input)",
        "ds-brand":   "0 0 16px rgba(167,139,250,0.35)",
        "ds-ring":    "0 0 0 1px rgba(255,255,255,0.08)",
        "ds-ring-md": "0 0 0 1px rgba(167,139,250,0.35)",
        "ds-ring-dark":"0 0 0 1px rgba(255,255,255,0.14)",
        "ds-whisper": "0 4px 24px rgba(0,0,0,0.35)",
        "ds-modal2":  "0 0 0 1px rgba(255,255,255,0.08), 0 24px 64px rgba(0,0,0,0.7)",
      },
      borderRadius: {
        "ds-xs":  "4px",
        "ds-sm":  "6px",
        "ds-md":  "10px",
        "ds-lg":  "14px",
        "ds-xl":  "18px",
        "ds-2xl": "24px",
        "ds-3xl": "32px",
      },
      backgroundImage: {
        "grad-brand":   "linear-gradient(135deg, #a78bfa 0%, #38bdf8 100%)",
        "grad-brand-r": "linear-gradient(135deg, #38bdf8 0%, #a78bfa 100%)",
        "grad-glass":   "linear-gradient(135deg, rgba(255,255,255,0.06) 0%, rgba(255,255,255,0.02) 100%)",
        "grad-sidebar": "linear-gradient(180deg, rgba(167,139,250,0.04) 0%, transparent 40%)",
        "shimmer":      "linear-gradient(90deg, transparent 0%, rgba(167,139,250,0.15) 50%, transparent 100%)",
      },
      animation: {
        "fade-in":    "fadeIn 0.2s ease-out",
        "scale-in":   "scaleIn 0.2s cubic-bezier(0.34,1.56,0.64,1)",
        "slide-in":   "slideInLeft 0.25s cubic-bezier(0.34,1.56,0.64,1)",
        "pulse-dot":  "pulseDot 1.4s ease-in-out infinite",
        "float":      "floatUp 3s ease-in-out infinite",
        "glow-pulse": "glowPulse 2s ease-in-out infinite",
        "shimmer":    "shimmer 2s linear infinite",
      },
      keyframes: {
        fadeIn:     { from: { opacity: "0", transform: "translateY(4px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        scaleIn:    { from: { opacity: "0", transform: "scale(0.92)" },     to: { opacity: "1", transform: "scale(1)" } },
        slideInLeft:{ from: { transform: "translateX(-100%)", opacity: "0" }, to: { transform: "translateX(0)", opacity: "1" } },
        pulseDot: {
          "0%, 80%, 100%": { transform: "scale(0)",   opacity: "0.4" },
          "40%":           { transform: "scale(1.2)", opacity: "1"   },
        },
        floatUp:    { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-4px)" } },
        glowPulse:  { "0%, 100%": { opacity: "0.6" }, "50%": { opacity: "1" } },
        shimmer:    { "0%": { backgroundPosition: "-200% center" }, "100%": { backgroundPosition: "200% center" } },
      },
      backdropBlur: {
        xs: "4px",
      },
    },
  },
  plugins: [],
};

export default config;
